---
- name: Install nagios
  apt:
    name:
      - build-essential
      - apache2
      - php
      - openssl
      - perl
      - make
      - php-gd
      - libgd-dev
      - libapache2-mod-php
      - libperl-dev
      - libssl-dev
      - daemon
      - wget
      - apache2-utils
      - unzip

- name: add group nagcmd
  group:
    name: nagcmd
    state: present

- name: add user nagios
  user:
    name: nagios
    group: nagcmd
- name: Install nagios plugins
  unarchive: 
    src: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /tmp
    remote_src: yes

- name: Configure nagios plugins
  command: ./configure --with-nagios-user=nagios --with-nagios-grou=nagcmd
  args:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configure using make
  make:
    chdir: /tmp/nagios-plugins-2.3.3

- name: Configure using make install
  make: 
    target: install
    chdir: /tmp/nagios-plugins-2.3.3
