---
# tasks file for roles/Elk_Monitoring_Centos
- name: Add the gpg key
  command: sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add the elasticsearch rpm repo
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Updating centos
  yum:
    update_cache: yes

- name: Insatalling elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: Installing kibana
  yum:
    name: kibana
    state: present

- name: Installing filebeat
  yum:
    name: filebeat
    state: present

- name: Installing logstash
  yum:
    name: logstash
    state: present

